# Generated by Django 3.1.3 on 2020-11-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('il', models.CharField(max_length=128)),
                ('hiz', models.FloatField()),
                ('lezzet', models.FloatField()),
                ('servis', models.FloatField()),
                ('acilis_zamani', models.TimeField()),
                ('kapanis_zamani', models.TimeField()),
                ('haftaici', models.BooleanField(default=True)),
                ('haftasonu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_hiz', models.FloatField()),
                ('yorum_lezzet', models.FloatField()),
                ('yorum_servis', models.FloatField()),
                ('yorum_date', models.DateTimeField()),
                ('yorum_icerik', models.TextField()),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ne_yesem.restoran')),
            ],
        ),
        migrations.CreateModel(
            name='Semt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semt_adi', models.CharField(max_length=128)),
                ('mahalle_adi', models.CharField(max_length=128)),
                ('minimum_tutar', models.FloatField()),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ne_yesem.restoran')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yemek', models.CharField(max_length=128)),
                ('fiyat', models.FloatField()),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ne_yesem.restoran')),
            ],
        ),
    ]
