# Generated by Django 3.1.3 on 2020-11-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ne_yesem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semt',
            old_name='mahalle_adi',
            new_name='semt_mahalle_adi',
        ),
        migrations.RemoveField(
            model_name='semt',
            name='semt_adi',
        ),
    ]
